name: Build App

on:
  push:
    tags:
      - 'v[0-9]+.*'
      
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keithlinneman/build-system@sha256:f054597ca033a3e8108e28bb096a21827ae4c75b399cf774233b640ad4812eb1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::148142827637:role/app-trustportal-build
          aws-region: us-east-2

      - name: Run checks (lint, tests, etc)
        run: make check

      - name: Build and release
        run: |
          /build-system/build.sh \
            --repo . \
            --ref ${{ github.sha }} \
            --track stable
